# Generated by Django 5.1.3 on 2024-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='companies', to='student.student'),
        ),
    ]
