# Generated by Django 5.1.3 on 2024-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('ph_no', models.IntegerField(unique=True)),
                ('branch', models.CharField(max_length=25)),
            ],
        ),
    ]
