# Generated by Django 5.1.3 on 2024-11-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_code',
            field=models.CharField(default='A1', max_length=26),
        ),
    ]
