# Generated by Django 5.1.3 on 2024-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_batch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ph_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
